### ISSUE TITLE
mashup/aggregate 

### ISSUE THREAD

**Issue by tomdavidson** [Tallyb/loopback-graphql#10]
What would it take to mashup/aggregate multiple data sources (rest apis) into new models exposed by rest and graphql?

**Comment by Tallyb** [comment]
I believe this is supported by Loopback itself, hence should also work with Graphql. Do you see any specific issue?

**Comment by tomdavidson** [comment]
Does it require double the glue? Im inexperienced with loopback sand my concern might not be specific to loopback-graphql.  I generate models by importing my swagger doc and use loopback-connector-swagger to connect the internal APIs ... not quite sure how to put it all together.

**Comment by Tallyb** [comment]
Can you provide a sample use case for what you are trying to achieve?

**Comment by tomdavidson** [comment]
We have a few dozen internal apis that we are will publish as a
universal/unified api - aggregate. Some of the published api rest endpoints
involve multiple internal apis - mashup. Rest is required for the published
api but I also want to publish GraphQL.

**Comment by Tallyb** [comment]
@tomdavidson - I am still having hard time following the issue. Is that something very specific, or do you think that will interest wider audience? 
In general I find that if you are not using strongly typed APIs, REST better suited for the job than Graphql.

**Comment by tomdavidson** [comment]
Thanks for the discussion Tallyb. I think the audience would include all BFFs and other public facing APIs that have multiple data sources.  

1. loopback-graphql creates its schemas automatically from the models so there is no need for extra glue code?
2. how are depreciations handled?
3. plans for subscriptions?

**Comment by Tallyb** [comment]
1. True. Everything defined in the models should be created as the graphql schema. 
2. For now - they are skipped. 
3. Now when they start mature, I will look into it.

**Comment by Tallyb** [comment]
Closing for now. Let me know if you have more questions
