### ISSUE TITLE
unable to query multiple items

### ISSUE THREAD

**Issue by tvojtech** [Tallyb/loopback-graphql#32]
Having simple model 

````
{
  "name": "secret",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "service": {
      "type": "string",
      "required": true
    },
    "email": {
      "type": "string"
    },
    "username": {
      "type": "string"
    },
    "password": {
      "type": "string"
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}
````

I can query single item, e.g. 
````
{
  secret (id:"5897957365e8144a83a34527") {
    id
    service
  }
}
````

but query for multiple items

````
{
  secret {
    id
    service
  }
}
````

ends with 

````
{
  "errors": [
    {
      "message": "Field \"secret\" argument \"id\" of type \"ID!\" is required but not provided.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ]
    }
  ]
}
````

Am I doing something wrong?

**Comment by Tallyb** [comment]
@tvojtech Can you retry with an id field which is marked with id: true ?

**Comment by tvojtech** [comment]
Same result. 

I found out that I can get list with 

````
{
  allSecrets {
    secrets {
      id
      service
    }
  }
}
````

works and gives me

````
{
  "data": {
    "allSecrets": {
      "secrets": [
        {
          "id": "5899df40280abf0d66f158ee",
          "service": "some service"
        }
      ]
    }
  }
}
````

but is this ok? I suppose the query 

````
{
  secret {
    id
    service
  }
}
````

should work.

**Comment by Tallyb** [comment]
@tvojtech sorry - it should not work with secret only. For querying multiple entities, you should use the allXXXX (XXXX = model name). 
If you are using graphiql, you can see that in the docs (on the right panel).

**Comment by tvojtech** [comment]
Is this common in GraphQL? I thought it's common to query single and multiple results same way (just added or avoiding filter condition) as described [here](http://jaketrent.com/post/return-array-graphql/).

Is this caused by `loopback-graphql` implementation?

**Comment by Tallyb** [comment]
It is how swapi is implemented. http://graphql.org/swapi-graphql/
I am not aware of any actual "standard". 
I would still imagine that you will have different queries - such as "secret" and "secrets". 

Thanks for trying out loopback-graphql!
