### ISSUE TITLE
Problem running . node graphql/utilities/buildASTSchema.js:266

### ISSUE THREAD

**Issue by patricktsg** [Tallyb/loopback-graphql#33]
I installed via NPM and added this to my component-config.json but get the following error

{
  "loopback-component-explorer": {
    "mountPath": "/explorer"
  },
  "loopback-graphql": {
    "path": "/graphql",
    "graphiqlPath":"/graphiql"
  }
}

node_modules/graphql/utilities/buildASTSchema.js:266
      throw new Error('Type "' + typeName + '" not found in document.');
      ^

Error: Type "undefined" not found in document.

**Comment by Tallyb** [comment]
Can you share your model?

**Comment by artalat** [comment]
i had the same error, removing geopoint property fixed it.

**Comment by Tallyb** [comment]
Geopoint was added in 0.12.
