### ISSUE TITLE
allXXX methods where parameter 

### ISSUE THREAD

**Issue by agarciagan** [Tallyb/loopback-graphql#37]
I have just integrated the plugin into an existing loopback application. The auto generated allXXX methods have a where parameter of type JSON.
I can use this parameter with equals operations, for example:
`  allEventStates(where: {timestamp: 1487690850276}) {`

But loopback filters have more [operators available](https://loopback.io/doc/en/lb2/Where-filter.html#operators) . Are these other operators from loopback available to the GraphQL queries when using this plugin? 

Thanks

**Comment by Tallyb** [comment]
Thank you for trying this plugin! 
I believe it should work, as the parameter is being moved to the find. 
Would you share your findings?

**Comment by agarciagan** [comment]
Calling directly a GET service from the loopback REST API works
`filter={"where":{"stateId":{"inq":["58ac5a7137f2f030e0396491"]}}}` 

Using the GraphiQl web interface I can use the equal filter:
`allXXX` (where:{stateId:"58ac5a7137f2f030e0396491"} )`

But not any variations. For example:
`allEventStates(where: {stateId: {in: ["58ac5a7137f2f030e0396491"]}}) {`
gives me an error

and `allStates(where: {id: [{inq:["58ac5a7137f2f030e0396491"]}]}) ` 
gives no error but returns no result

**Comment by Tallyb** [comment]
Can you just copy the same string as you put in the loopback explorer filter field and send it on the where? (with all quotations marks etc?)

**Comment by agarciagan** [comment]
No luck.

Direct GET API call works:
`http://localhost:3000/api/States?filter={"where":{"code":{"inq":["11"]}}}`  
gives me the correct result.

Using GraphiQL does not work:
``  allStates(where:"code:{inq:[\"11\"]}")  
 gives me "The where argument must be an object"

`allStates(where:{code:{inq:["11"]}})` 
 gives me       "message": "Cannot convert object to primitive value",

**Comment by Tallyb** [comment]
@agarciagan  I checked it with test 'should return response with where on id' on query.spec. 
Seems to work fine.

**Comment by agarciagan** [comment]
Thanks Tallyb,
Following the [test](https://github.com/Tallyb/loopback-graphql/blob/7b166977ddfb9934273709fc10b15f914dfc298b/test/query.spec.js) I have checked that passing the where parameters as variables works. 
`        
 query users ($where:JSON){
                  allUsers(where: $where) {
                    totalCount
                    edges {
                      node {
                        id
                        email
                      }
                    }                    
                  }
      }
`
 `           const variables = {
                where: {
                    id: {
                        inq: [1, 2]
                    }
                }
            };`
