### ISSUE TITLE
[Question] How do I log in?

### ISSUE THREAD

**Issue by Industrial** [Tallyb/loopback-graphql#4]
Hi!

great project! I am using Apollo server in my project and I was just about to map out the API for sessions / login when I saw your project.

When I look in Graphiql there are the methods saveUser and deleteUser. There's no mutation for all the other types/things.

When I query for BlogPosts (hasMany BlogComment) I can't get the comments out. This is where I'm doing it manually; https://gist.github.com/Industrial/5342b9dbc41ecc601c9996c4eb28d8a6

**Comment by Tallyb** [comment]
@Industrial  Thanks for your support. 

This project is WIP, and I am aware that many things are still  missing... :)
Remote methods (such as login / logout) is surely one of them. 

As for query "has many" relationships - this should work. Look at the code here: https://github.com/Tallyb/loopback-graphql/blob/master/lib/resolvers.js#L34

The resolve object gets an obj param that contains its parent context, and then I use it to query the related items.

**Comment by Tallyb** [comment]
@Industrial  I am closing it for now. Please re-open if it is still an issue.
