### ISSUE TITLE
Error Type Image Field MSSQL

### ISSUE THREAD

**Issue by gsancho** [Tallyb/loopback-graphql#47]
I have a model with an image type field from mssql database. 
But does not recognize correctly.

"ximagen": {
			"type": "Binary",
			"required": false,
			"length": 2147483647,
			"precision": null,
			"scale": null,
			"mssql": {
				"columnName": "ximagen",
				"dataType": "image",
				"dataLength": 2147483647,
				"dataPrecision": null,
				"dataScale": null,
				"nullable": "YES"
			}
		}

**Comment by Tallyb** [comment]
Is this a loopback supported type?

**Comment by gsancho** [comment]
Nop,

**Comment by Tallyb** [comment]
Mmmm....
