### ISSUE TITLE
{"errors":[{"message":"Must provide document"}]}

### ISSUE THREAD

**Issue by beiluo** [Tallyb/loopback-graphql#50]
i clone this repo,when i run it,it report a error.
{"errors":[{"message":"Must provide document"}]}

**Comment by Tallyb** [comment]
Can you specify exactly how you run it?

**Comment by beiluo** [comment]
npm run server

**Comment by Tallyb** [comment]
Not sure why this happened. Can you make sure you npm install ran correctly? I just did a test myself and it seemed to work fine. 
Also - see if you can provide additional information.
