### ISSUE TITLE
cannot get graphql running

### ISSUE THREAD

**Issue by jmls** [Tallyb/loopback-graphql#70]
so, and I am feeling _really_ stupid here, I cannot get this to work. I have followed the instructions, and the loopback server comes up, but nothing happens when I try to access /graphiql

I have a sneaking suspicion that I also need to install some server-side graphql server ... or do I ?

**Comment by Tallyb** [comment]
Hi, 
You will need a loopback server. Then install this package and add the configuration as described in the readme. Once running your loopback server, you should be able to see your graphql / graphiql. 
Does your /explorer end point works?

**Comment by jmls** [comment]
Thanks for the feedback - I already have a running loopback server, and added all the config as described. My /explorer endpoint works just fine. 

I am running angular-cli, so also added /graphql etc to the proxy.conf.json file as well

**Comment by Tallyb** [comment]
Can you check that you get any response from <you-all>/GraphiQL?

**Comment by jmls** [comment]
no, I don't - the backend has a catchall and tries to deliver the index.html

**Comment by Tallyb** [comment]
Can you share your component config? Compare it with the repo's sample?

**Comment by jmls** [comment]
sure

```
{
  "loopback-component-explorer": {
    "mountPath": "/explorer"
  },

  "loopback-graphql": {
    "path": "/graphql",
    "graphiqlPath":"/graphiql"
  }
}
```

**Comment by Tallyb** [comment]
I suggest that you will debug the loopback boot to ensure it goes thru this configuration. I am having trouble trying to understand what is the issue.

**Comment by jmls** [comment]
ok, so I feel really _stupid_. My catchall didn't have the grapql exception ... so sorry ;)

So now it's up and running. At least I can get to graphiql - but there is no schema. Is there an api to generate the schema from the looopback models ?

**Comment by Tallyb** [comment]
It is generating the schema. Possibly, something failed.

**Comment by jmls** [comment]
odd. `abstractTypes()` seems to return the correct information

```
TaskLabel: 
   { category: 'TYPE',
     input: true,
     fields: 
      { taskId: [Object],
        labelId: [Object],
        id: [Object],
        label: [Object],
        task: [Object] } },
  TaskLabelConnection: 
   { connection: true,
     category: 'TYPE',
     fields: 
      { pageInfo: [Object],
        edges: [Object],
        totalCount: [Object],
        TaskLabels: [Object] },
     resolver: [Function: resolver] },
  TaskLabelEdge: 
   { category: 'TYPE',
     fields: { node: [Object], cursor: [Object] } },
```
etc for each shared model

**Comment by jmls** [comment]
and `makeExecutableSchema()` also returns data that looks valid and correct

**Comment by jmls** [comment]
and now .. it pops up. Just ignore me :)

**Comment by Tallyb** [comment]
No problem. Thank you for using it. Feel free to star it...
